import type { Employee, Department, SalaryHistory } from './types'

export const mockDepartments: Department[] = [
  { id: 'd1', name: 'خدمات', employeeCount: 5, createdAt: new Date() },
  { id: 'd2', name: 'ضيافة', employeeCount: 4, createdAt: new Date() },
  { id: 'd3', name: 'شاورما', employeeCount: 3, createdAt: new Date() },
  { id: 'd4', name: 'كيك', employeeCount: 2, createdAt: new Date() },
  { id: 'd5', name: 'إيطالي', employeeCount: 3, createdAt: new Date() },
  { id: 'd6', name: 'بار', employeeCount: 2, createdAt: new Date() },
  { id: 'd7', name: 'حلويات شرقية', employeeCount: 2, createdAt: new Date() },
  { id: 'd8', name: 'كول سنتر', employeeCount: 3, createdAt: new Date() },
  { id: 'd9', name: 'مصنع', employeeCount: 4, createdAt: new Date() },
  { id: 'd10', name: 'ضبط جودة', employeeCount: 2, createdAt: new Date() },
  { id: 'd11', name: 'كاشيرات', employeeCount: 3, createdAt: new Date() },
  { id: 'd12', name: 'إدارة', employeeCount: 2, createdAt: new Date() },
]

export const mockEmployees: Employee[] = [
  {
    id: '1',
    employeeId: 'E20001',
    fullName: 'أحمد محمد علي',
    department: 'إدارة',
    departmentId: 'd12',
    baseSalary: 5000,
    workHours: 200,
    withdrawals: 500,
    deductions: 100,
    remaining: 4400,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    password: 'admin123',
    role: 'admin',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '2',
    employeeId: 'E20002',
    fullName: 'سارة أحمد خالد',
    department: 'إدارة',
    departmentId: 'd12',
    baseSalary: 4500,
    workHours: 180,
    withdrawals: 200,
    deductions: 50,
    remaining: 4250,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    password: 'hr123',
    role: 'hr',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '3',
    employeeId: 'E20003',
    fullName: 'محمد عبدالله حسن',
    department: 'خدمات',
    departmentId: 'd1',
    baseSalary: 3000,
    workHours: 220,
    withdrawals: 1000,
    deductions: 200,
    remaining: 1800,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    password: '0003',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '4',
    employeeId: 'E20004',
    fullName: 'فاطمة يوسف سعيد',
    department: 'ضيافة',
    departmentId: 'd2',
    baseSalary: 2800,
    workHours: 200,
    withdrawals: 2300,
    deductions: 100,
    remaining: 400,
    paymentStatus: 'cash',
    cashDays: 5,
    password: '0004',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '5',
    employeeId: 'E20005',
    fullName: 'علي حسين محمود',
    department: 'شاورما',
    departmentId: 'd3',
    baseSalary: 3200,
    workHours: 240,
    withdrawals: 500,
    deductions: 0,
    remaining: 2700,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    password: '0005',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '6',
    employeeId: 'E20006',
    fullName: 'نور الدين أحمد',
    department: 'كيك',
    departmentId: 'd4',
    baseSalary: 2900,
    workHours: 190,
    withdrawals: 800,
    deductions: 100,
    remaining: 2000,
    paymentStatus: 'processing',
    cashDays: 3,
    password: '0006',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '7',
    employeeId: 'E20007',
    fullName: 'ريم سامي عبدالرحمن',
    department: 'إيطالي',
    departmentId: 'd5',
    baseSalary: 3100,
    workHours: 210,
    withdrawals: 2600,
    deductions: 150,
    remaining: 350,
    paymentStatus: 'cash',
    cashDays: 4,
    password: '0007',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '8',
    employeeId: 'E20008',
    fullName: 'خالد عمر فؤاد',
    department: 'بار',
    departmentId: 'd6',
    baseSalary: 2700,
    workHours: 180,
    withdrawals: 300,
    deductions: 50,
    remaining: 2350,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    password: '0008',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '9',
    employeeId: 'E20009',
    fullName: 'هدى محمد سليم',
    department: 'حلويات شرقية',
    departmentId: 'd7',
    baseSalary: 2850,
    workHours: 195,
    withdrawals: 400,
    deductions: 75,
    remaining: 2375,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    password: '0009',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '10',
    employeeId: 'E20010',
    fullName: 'ياسر عادل كريم',
    department: 'كول سنتر',
    departmentId: 'd8',
    baseSalary: 2600,
    workHours: 200,
    withdrawals: 2100,
    deductions: 0,
    remaining: 500,
    paymentStatus: 'cash',
    cashDays: 3,
    password: '0010',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '11',
    employeeId: 'E20011',
    fullName: 'مريم عبدالله ناصر',
    department: 'مصنع',
    departmentId: 'd9',
    baseSalary: 3300,
    workHours: 230,
    withdrawals: 700,
    deductions: 200,
    remaining: 2400,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    password: '0011',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '12',
    employeeId: 'E20012',
    fullName: 'عمر حسن جمال',
    department: 'ضبط جودة',
    departmentId: 'd10',
    baseSalary: 3500,
    workHours: 200,
    withdrawals: 500,
    deductions: 100,
    remaining: 2900,
    paymentStatus: 'processing',
    cashDays: 3,
    password: '0012',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '13',
    employeeId: 'E20013',
    fullName: 'لينا سعد توفيق',
    department: 'كاشيرات',
    departmentId: 'd11',
    baseSalary: 2500,
    workHours: 185,
    withdrawals: 1900,
    deductions: 50,
    remaining: 550,
    paymentStatus: 'cash',
    cashDays: 3,
    password: '0013',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '14',
    employeeId: 'E20014',
    fullName: 'طارق مصطفى رشيد',
    department: 'خدمات',
    departmentId: 'd1',
    baseSalary: 2800,
    workHours: 210,
    withdrawals: 600,
    deductions: 100,
    remaining: 2100,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    password: '0014',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '15',
    employeeId: 'E20015',
    fullName: 'دينا أحمد فايز',
    department: 'ضيافة',
    departmentId: 'd2',
    baseSalary: 2750,
    workHours: 190,
    withdrawals: 400,
    deductions: 75,
    remaining: 2275,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    password: '0015',
    role: 'employee',
    createdAt: new Date(),
    updatedAt: new Date()
  }
]

export const mockSalaryHistory: SalaryHistory[] = [
  {
    id: 'sh1',
    employeeId: 'E20003',
    month: 'يناير',
    year: 2024,
    baseSalary: 3000,
    workHours: 200,
    withdrawals: 500,
    deductions: 100,
    remaining: 2400,
    paymentStatus: 'bank_transfer',
    paidAt: new Date('2024-01-28'),
    createdAt: new Date('2024-01-01')
  },
  {
    id: 'sh2',
    employeeId: 'E20003',
    month: 'فبراير',
    year: 2024,
    baseSalary: 3000,
    workHours: 180,
    withdrawals: 800,
    deductions: 150,
    remaining: 2050,
    paymentStatus: 'bank_transfer',
    paidAt: new Date('2024-02-28'),
    createdAt: new Date('2024-02-01')
  },
  {
    id: 'sh3',
    employeeId: 'E20003',
    month: 'مارس',
    year: 2024,
    baseSalary: 3000,
    workHours: 220,
    withdrawals: 1000,
    deductions: 200,
    remaining: 1800,
    paymentStatus: 'bank_transfer',
    paidAt: new Date('2024-03-28'),
    createdAt: new Date('2024-03-01')
  },
  {
    id: 'sh4',
    employeeId: 'E20004',
    month: 'يناير',
    year: 2024,
    baseSalary: 2800,
    workHours: 190,
    withdrawals: 1500,
    deductions: 100,
    remaining: 1200,
    paymentStatus: 'bank_transfer',
    paidAt: new Date('2024-01-28'),
    createdAt: new Date('2024-01-01')
  },
  {
    id: 'sh5',
    employeeId: 'E20004',
    month: 'فبراير',
    year: 2024,
    baseSalary: 2800,
    workHours: 200,
    withdrawals: 2000,
    deductions: 150,
    remaining: 650,
    paymentStatus: 'cash',
    paidAt: new Date('2024-02-28'),
    createdAt: new Date('2024-02-01')
  },
  {
    id: 'sh6',
    employeeId: 'E20004',
    month: 'مارس',
    year: 2024,
    baseSalary: 2800,
    workHours: 200,
    withdrawals: 2300,
    deductions: 100,
    remaining: 400,
    paymentStatus: 'cash',
    paidAt: null,
    createdAt: new Date('2024-03-01')
  }
]
